-- 1. Create the views table
CREATE TABLE site_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash TEXT NOT NULL,
  visited_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  -- The core logic: ensures 1 unique visitor per day ONLY
  UNIQUE(ip_hash, visited_date) 
);

-- Enable RLS and allow anonymous inserts
ALTER TABLE site_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous inserts" ON site_views FOR INSERT WITH CHECK (true);

-- 2. Create the fast RPC function to calculate the metrics
CREATE OR REPLACE FUNCTION get_view_metrics()
RETURNS TABLE(total_views BIGINT, unique_visitors BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  SELECT 
    (SELECT COUNT(*) FROM site_views) AS total_views,
    (SELECT COUNT(DISTINCT ip_hash) FROM site_views) AS unique_visitors;
END;
$$;
