-- 1. Create the views table
CREATE TABLE IF NOT EXISTS site_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash TEXT NOT NULL,
  visited_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  -- The core logic: ensures 1 unique visitor per day ONLY
  UNIQUE(ip_hash, visited_date) 
);

-- 2. Drop existing policies to prevent conflicts
DROP POLICY IF EXISTS "Allow anonymous inserts" ON site_views;
DROP POLICY IF EXISTS "Allow public access" ON site_views;

-- 3. Enable RLS but create a full public policy to fix the UPSERT bug
ALTER TABLE site_views ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON site_views FOR ALL USING (true) WITH CHECK (true);

-- 4. Create the fast RPC function to calculate the metrics
CREATE OR REPLACE FUNCTION get_view_metrics()
RETURNS TABLE(total_views BIGINT, unique_visitors BIGINT)
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  SELECT 
    (SELECT COUNT(*) FROM site_views) AS total_views,
    (SELECT COUNT(DISTINCT ip_hash) FROM site_views) AS unique_visitors;
END;
$$;
